import type { ResolvedTokens } from './model.ts';

const HEADER = '/* Generated by @sipclock/tokens from src/tokens.json. Do not edit by hand. */\n';

const decls = (vars: Record<string, string>, prefix = '') =>
  Object.entries(vars)
    .map(([k, v]) => `  --${prefix}${k}: ${v};`)
    .join('\n');

/** Plain CSS custom properties. The first theme is also the :root default. */
export function emitCss(t: ResolvedTokens): string {
  const [first, ...rest] = t.themes;
  const themeBlock = (theme: string, selector: string) =>
    `${selector} {\n${decls(t.colors[theme] ?? {})}\n${decls(t.shadows[theme] ?? {})}\n  color-scheme: ${theme === 'day' ? 'light' : 'dark'};\n}`;
  const blocks = [
    themeBlock(first as string, `:root,\n[data-theme="${first}"]`),
    ...rest.map((theme) => themeBlock(theme, `[data-theme="${theme}"]`)),
    `:root {\n${decls(t.space)}\n${decls(t.radius)}\n${decls(t.fonts, 'font-')}\n}`,
  ];
  return `${HEADER}${blocks.join('\n\n')}\n`;
}

/** Tailwind v4 theme that maps utilities onto the CSS variables (bg-surface, rounded-lg, font-display…). */
export function emitTailwindTheme(t: ResolvedTokens): string {
  const colorNames = Object.keys(t.colors[t.themes[0] as string] ?? {});
  // Colors and shadows change per theme, so utilities point at the runtime variables.
  // Radius and fonts are theme-independent literals: re-declaring them as var(--same-name) would be circular.
  // Spacing needs no mapping: the token scale (4, 8, 12… 48) is Tailwind's default 4px scale.
  const lines = [
    ...colorNames.map((n) => `  --color-${n}: var(--${n});`),
    ...Object.entries(t.radius).map(([n, v]) => `  --${n}: ${v};`),
    ...Object.entries(t.fonts).map(([n, v]) => `  --font-${n}: ${v};`),
  ];
  const shadows = Object.keys(t.shadows[t.themes[0] as string] ?? {}).map(
    (n) => `@utility ${n} {\n  box-shadow: var(--${n});\n}`,
  );
  return `${HEADER}@theme inline {\n${lines.join('\n')}\n}\n\n${shadows.join('\n\n')}\n`;
}

/** Design theme id -> Uniwind's built-in theme variant. night is the dark theme, day the light one. */
export const UNIWIND_VARIANTS: Record<string, string> = { night: 'dark', day: 'light' };

/**
 * Uniwind (Tailwind v4 for React Native) stylesheet: per-theme color and shadow variables declared
 * under `@variant dark|light` (Uniwind's theming syntax, switches with the system color scheme),
 * plus theme-independent radius. Fonts are not mapped: React Native needs one loaded family per
 * weight, so the app maps the text styles from tokens.ts instead.
 */
export function emitUniwind(t: ResolvedTokens): string {
  const variantBlock = (theme: string) => {
    const variant = UNIWIND_VARIANTS[theme];
    if (!variant) throw new Error(`No Uniwind variant mapped for theme "${theme}"`);
    const colors = Object.entries(t.colors[theme] ?? {}).map(
      ([k, v]) => `      --color-${k}: ${v};`,
    );
    const shadows = Object.entries(t.shadows[theme] ?? {}).map(([k, v]) => `      --${k}: ${v};`);
    return `    @variant ${variant} {\n${[...colors, ...shadows].join('\n')}\n    }`;
  };
  const radius = Object.entries(t.radius).map(([n, v]) => `  --${n}: ${v};`);
  const shadows = Object.keys(t.shadows[t.themes[0] as string] ?? {}).map(
    (n) => `@utility ${n} {\n  box-shadow: var(--${n});\n}`,
  );
  return `${HEADER}@theme {\n${radius.join('\n')}\n}\n\n@layer theme {\n  :root {\n${t.themes.map(variantBlock).join('\n')}\n  }\n}\n\n${shadows.join('\n\n')}\n`;
}

/** Typed object for React Native and anywhere CSS variables are not available. */
export function emitTs(t: ResolvedTokens): string {
  const px = (v: string) => (v.endsWith('px') ? Number.parseFloat(v) : v);
  const numeric = (rec: Record<string, string>) =>
    Object.fromEntries(Object.entries(rec).map(([k, v]) => [k, px(v)]));
  const text = Object.fromEntries(
    Object.entries(t.text).map(([k, s]) => [
      k,
      {
        fontFamily: s.family,
        fontSize: px(s.fontSize),
        lineHeight: px(s.lineHeight),
        fontWeight: s.fontWeight,
        ...(s.letterSpacing ? { letterSpacing: s.letterSpacing } : {}),
      },
    ]),
  );
  const data = {
    themes: t.themes,
    colors: t.colors,
    space: numeric(t.space),
    radius: numeric(t.radius),
    fonts: t.fonts,
    text,
  };
  return `// Generated by @sipclock/tokens from src/tokens.json. Do not edit by hand.\n\nexport const tokens = ${JSON.stringify(data, null, 2)} as const;\n\nexport type ThemeName = (typeof tokens.themes)[number];\nexport type ColorName = keyof (typeof tokens.colors)['night'];\nexport type TextStyleName = keyof typeof tokens.text;\n`;
}
