import type { IngredientKind } from '@sipclock/domain';
import { type Locale, pluralCategory } from '@sipclock/i18n';

import type { SyncState } from './sync-status';

const pluralRu = (n: number, one: string, few: string, many: string) => {
  const form = pluralCategory('ru', n);
  return form === 'one' ? one : form === 'few' ? few : many;
};

const en = {
  now: 'Now',
  noAlcohol: 'No alcohol',
  makeIt: 'Make it',
  anotherIdea: 'Another idea',
  alsoGoodNow: 'Also good now',
  emptyTitle: 'Nothing fits right now',
  emptyHint: 'Try another occasion or add more to your bar.',
  alcAbbr: 'Alc.',
  freeAbbr: 'Free',
  abvLabel: (percent: number) => `${percent} percent alcohol`,
  alcoholFreeLabel: 'Alcohol free',
  timeLabel: (time: string) => `Current time ${time}`,
  availReady: 'All in your bar',
  availSwap: (n: number) => `Ready · ${n} ${n === 1 ? 'swap' : 'swaps'}`,
  availMissing: (names: string) => `Missing: ${names}`,
  back: 'Back',
  notFoundTitle: 'Drink not found',
  notFoundHint: 'This recipe is not in the catalog.',
  servings: 'Servings',
  decreaseServings: 'Fewer servings',
  increaseServings: 'More servings',
  units: { ml: 'ml', oz: 'oz', parts: 'Parts' } as Record<'ml' | 'oz' | 'parts', string>,
  ingredients: 'Ingredients',
  steps: 'Steps',
  optional: 'optional',
  garnish: 'garnish',
  have: 'In your bar',
  swapWith: (name: string) => `Swap: ${name}`,
  missing: 'Missing',
  barTitle: 'My bar',
  canMakeNow: (n: number) => `${n} ${n === 1 ? 'cocktail' : 'cocktails'} you can make now`,
  searchIngredients: 'Search ingredients',
  starterBar: 'Starter bar',
  clearBar: 'Clear bar',
  clearConfirm: 'Remove everything from your bar?',
  clearYes: 'Clear',
  cancel: 'Cancel',
  noResults: 'No ingredients found.',
  inBarCount: (n: number) => `${n} in your bar`,
  account: 'Account',
  signIn: 'Sign in',
  signInPitch: 'Sign in to keep your bar and favorites on all your devices.',
  guestNote:
    'Until then, everything stays on this device and moves to your account when you sign in.',
  email: 'Email',
  emailPlaceholder: 'you@example.com',
  sendCode: 'Send code',
  codeTitle: 'Enter the code',
  codeSentTo: (email: string) => `We sent a 6-digit code to ${email}.`,
  code: 'Code',
  resendCode: 'Resend code',
  resendIn: (seconds: number) => `Resend in ${seconds}s`,
  codeResent: 'New code sent.',
  useAnotherEmail: 'Use another email',
  usePassword: 'Use password',
  useCodeInstead: 'Use a code instead',
  password: 'Password',
  newPassword: 'New password',
  passwordHint: 'At least 8 characters',
  show: 'Show',
  hide: 'Hide',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  forgotPassword: 'Forgot password?',
  createAccount: 'Create account',
  createAccountPitch: 'Create an account to keep your bar and favorites on all your devices.',
  haveAccount: 'Back to sign in',
  confirmEmailTitle: 'Confirm your email',
  confirmEmailFirst: 'Confirm your email first. We sent you a code.',
  confirm: 'Confirm',
  forgotTitle: 'Reset password',
  forgotPitch: "Enter your email and we'll send a code to set a new password.",
  resetTitle: 'Set a new password',
  setPassword: 'Set password',
  setOrChangePassword: 'Set or change password',
  passwordUpdated: 'Password updated. Sign in with your new password.',
  errInvalidCredentials: 'Wrong email or password.',
  errEmailNotVerified: 'Confirm your email first. We sent you a code.',
  errPasswordShort: 'Use at least 8 characters.',
  errPasswordLong: 'Use at most 128 characters.',
  errPasswordCompromised: 'That password appeared in a data breach. Choose another one.',
  errEnterPassword: 'Enter your password.',
  errInvalidEmail: 'Enter a valid email address.',
  errInvalidCode: 'That code is wrong. Check it and try again.',
  errExpiredCode: 'That code has expired. Send a new one.',
  errTooManyAttempts: 'Too many attempts. Send a new code.',
  errRateLimited: 'Too many attempts. Try again later.',
  errNetwork: "Can't reach the server. Check your connection and try again.",
  errGeneric: 'Something went wrong. Try again.',
  errReauth: 'For your security, sign out, sign in again, then delete your account.',
  signedInAs: 'Signed in as',
  signOut: 'Sign out',
  signOutTitle: 'Sign out?',
  signOutBody: 'Your bar, favorites and history leave this device. They stay in your account.',
  signOutUnsynced: 'Some changes have not synced yet and will be lost.',
  deleteAccount: 'Delete account',
  deleteTitle: 'Delete account?',
  deleteBody:
    'This permanently deletes your account with your bar, favorites and history. You cannot undo it.',
  deleteYes: 'Delete',
  deleteCodePrompt: 'To confirm, enter the code we just sent to your email.',
  errCodeDidNotWork: 'That code did not work. Check it and try again.',
  history: 'History',
  historyEmpty: 'Drinks you make show up here. Tap I made it on a recipe.',
  sync: {
    guest: 'Saved on this device only',
    offline: 'Offline. Changes sync when you reconnect.',
    connecting: 'Connecting…',
    syncing: 'Syncing…',
    synced: 'Synced',
    error: 'Sync paused. Retrying.',
  } satisfies Record<SyncState, string>,
  syncedAt: (time: string) => `Synced at ${time}`,
  favoritesTitle: 'Favorites',
  favoritesEmptyTitle: 'No favorites yet',
  favoritesEmptyHint: 'Save drinks you like and they show up here.',
  findDrink: 'Find a drink',
  save: 'Save',
  saved: 'Saved',
  saveLabel: 'Save to favorites',
  unsaveLabel: 'Remove from favorites',
  madeIt: 'I made it',
  madeItDone: 'Added to your history.',
  swapFind: 'Find a swap',
  swapSignInHint: 'Sign in to get swaps for missing ingredients.',
  swapPick: 'Which ingredient do you want to swap?',
  swapNoIngredients: 'No ingredients to swap.',
  swapChipLabel: (name: string) => `Find a swap for ${name}`,
  swapLoading: 'Finding swaps',
  swapForTitle: (name: string) => `Swaps for ${name}`,
  swapAi: 'AI suggestion',
  swapQuotaReached: "Daily AI limit reached. Showing editors' picks.",
  swapInBar: 'In your bar',
  swapFitClose: 'Close match',
  swapFitWorkable: 'Different but good',
  swapCanSkip: 'You can also leave it out.',
  swapEmpty: 'No good swap in our catalog.',
  swapError: "Couldn't load swaps.",
  swapRetry: 'Try again',
  swapCount: (n: number) => `${n} ${n === 1 ? 'swap' : 'swaps'} found`,
  todayTab: 'Today',
  searchTab: 'Search',
  bartenderTab: 'Bartender',
  bartenderTitle: 'Bartender',
  chatNew: 'New chat',
  chatSignedOutTitle: 'Sign in to ask the bartender',
  chatSignedOutHint:
    'The bartender knows your bar and favorites, so answers fit what you have at home.',
  chatSignIn: 'Sign in',
  chatSeePick: 'See today\u2019s pick',
  chatEmptyTitle: 'Ask the bartender',
  chatEmptyHint: 'What to make from your bar, how to swap an ingredient, what suits tonight.',
  chatStarters: [
    'What can I make right now?',
    'Something light and citrusy',
    'What can replace vermouth in a Negroni?',
    'An alcohol-free drink for tonight',
  ],
  chatAnswering: 'The bartender is answering\u2026',
  chatPlaceholder: 'Ask about drinks or swaps',
  chatInputLabel: 'Message the bartender',
  chatSend: 'Send',
  chatYouSaid: 'You',
  chatBartenderSaid: 'Bartender',
  chatQuotaLeft: (n: number) => `${n} left today \u00b7 Answers can be wrong.`,
  chatQuotaUnknown: 'Answers can be wrong.',
  chatLimitTitle: 'That\u2019s all 15 questions for today',
  chatLimitHint:
    'New questions open at midnight. Recipes, your bar and catalog swaps work as usual.',
  chatFailTitle: 'Couldn\u2019t answer right now',
  chatFailHint: 'Try again in a minute.',
  chatBusyTitle: 'Still answering your last question',
  chatRetry: 'Try again',
  chatTools: {
    get_my_bar: 'Checked your bar',
    what_can_i_make: 'Checked what you can make',
    search_recipes: 'Searched recipes',
    get_recipe: 'Looked up the recipe',
    find_substitutes: 'Looked up swaps',
    recommend_now: 'Picked for right now',
  } as Record<string, string>,
  kinds: {
    spirit: 'Spirits',
    liqueur: 'Liqueurs',
    wine: 'Wine',
    beer: 'Beer',
    bitters: 'Bitters',
    syrup: 'Syrups',
    juice: 'Juices',
    mixer: 'Mixers',
    fresh: 'Fresh',
    dairy: 'Dairy',
    pantry: 'Pantry',
    staple: 'Staples',
  } satisfies Record<IngredientKind, string>,
};

export type Strings = typeof en;

const ru: Strings = {
  now: 'Сейчас',
  noAlcohol: 'Без алкоголя',
  makeIt: 'Приготовить',
  anotherIdea: 'Другая идея',
  alsoGoodNow: 'Ещё подойдёт',
  emptyTitle: 'Сейчас ничего не подходит',
  emptyHint: 'Выберите другой повод или пополните бар.',
  alcAbbr: 'Алк.',
  freeAbbr: 'Без алк.',
  abvLabel: (percent) => `${percent} процентов алкоголя`,
  alcoholFreeLabel: 'Без алкоголя',
  timeLabel: (time) => `Сейчас ${time}`,
  availReady: 'Всё есть в баре',
  availSwap: (n) => `Готово · ${n} ${pluralRu(n, 'замена', 'замены', 'замен')}`,
  availMissing: (names) => `Не хватает: ${names}`,
  back: 'Назад',
  notFoundTitle: 'Напиток не найден',
  notFoundHint: 'Этого рецепта нет в каталоге.',
  servings: 'Порции',
  decreaseServings: 'Меньше порций',
  increaseServings: 'Больше порций',
  units: { ml: 'мл', oz: 'oz', parts: 'Части' },
  ingredients: 'Ингредиенты',
  steps: 'Шаги',
  optional: 'по желанию',
  garnish: 'украшение',
  have: 'Есть в баре',
  swapWith: (name) => `Замена: ${name}`,
  missing: 'Нет',
  barTitle: 'Мой бар',
  canMakeNow: (n) =>
    `${n} ${pluralRu(n, 'коктейль', 'коктейля', 'коктейлей')} можно приготовить сейчас`,
  searchIngredients: 'Поиск ингредиентов',
  starterBar: 'Базовый бар',
  clearBar: 'Очистить бар',
  clearConfirm: 'Убрать всё из бара?',
  clearYes: 'Очистить',
  cancel: 'Отмена',
  noResults: 'Ингредиенты не найдены.',
  inBarCount: (n) => `В баре: ${n}`,
  account: 'Аккаунт',
  signIn: 'Войти',
  signInPitch: 'Войдите, чтобы бар и избранное были на всех ваших устройствах.',
  guestNote: 'Пока всё хранится на этом устройстве и перейдёт в аккаунт, когда вы войдёте.',
  email: 'Почта',
  emailPlaceholder: 'you@example.com',
  sendCode: 'Отправить код',
  codeTitle: 'Введите код',
  codeSentTo: (email) => `Мы отправили 6-значный код на ${email}.`,
  code: 'Код',
  resendCode: 'Отправить ещё раз',
  resendIn: (seconds) => `Повторить через ${seconds} с`,
  codeResent: 'Новый код отправлен.',
  useAnotherEmail: 'Другая почта',
  usePassword: 'Войти по паролю',
  useCodeInstead: 'Войти по коду',
  password: 'Пароль',
  newPassword: 'Новый пароль',
  passwordHint: 'Не короче 8 символов',
  show: 'Показать',
  hide: 'Скрыть',
  showPassword: 'Показать пароль',
  hidePassword: 'Скрыть пароль',
  forgotPassword: 'Забыли пароль?',
  createAccount: 'Создать аккаунт',
  createAccountPitch: 'Создайте аккаунт, чтобы бар и избранное были на всех ваших устройствах.',
  haveAccount: 'Назад ко входу',
  confirmEmailTitle: 'Подтвердите почту',
  confirmEmailFirst: 'Сначала подтвердите почту. Мы отправили вам код.',
  confirm: 'Подтвердить',
  forgotTitle: 'Сброс пароля',
  forgotPitch: 'Введите почту, и мы отправим код для нового пароля.',
  resetTitle: 'Задайте новый пароль',
  setPassword: 'Сохранить пароль',
  setOrChangePassword: 'Задать или сменить пароль',
  passwordUpdated: 'Пароль обновлён. Войдите с новым паролем.',
  errInvalidCredentials: 'Неверная почта или пароль.',
  errEmailNotVerified: 'Сначала подтвердите почту. Мы отправили вам код.',
  errPasswordShort: 'Нужно не меньше 8 символов.',
  errPasswordLong: 'Нужно не больше 128 символов.',
  errPasswordCompromised: 'Этот пароль найден в утечках данных. Выберите другой.',
  errEnterPassword: 'Введите пароль.',
  errInvalidEmail: 'Введите корректный адрес почты.',
  errInvalidCode: 'Неверный код. Проверьте и попробуйте снова.',
  errExpiredCode: 'Срок действия кода истёк. Запросите новый.',
  errTooManyAttempts: 'Слишком много попыток. Запросите новый код.',
  errRateLimited: 'Слишком много попыток. Попробуйте позже.',
  errNetwork: 'Нет связи с сервером. Проверьте подключение и попробуйте снова.',
  errGeneric: 'Что-то пошло не так. Попробуйте снова.',
  errReauth: 'Для безопасности выйдите, снова войдите и затем удалите аккаунт.',
  signedInAs: 'Вы вошли как',
  signOut: 'Выйти',
  signOutTitle: 'Выйти?',
  signOutBody: 'Бар, избранное и история удалятся с этого устройства, но останутся в аккаунте.',
  signOutUnsynced: 'Часть изменений ещё не синхронизирована и пропадёт.',
  deleteAccount: 'Удалить аккаунт',
  deleteTitle: 'Удалить аккаунт?',
  deleteBody: 'Аккаунт, бар, избранное и история будут удалены навсегда. Отменить это нельзя.',
  deleteYes: 'Удалить',
  deleteCodePrompt: 'Для подтверждения введите код, который мы только что отправили на почту.',
  errCodeDidNotWork: 'Код не подошёл. Проверьте и попробуйте снова.',
  history: 'История',
  historyEmpty: 'Здесь появятся напитки, которые вы приготовили. Нажмите «Приготовлено» в рецепте.',
  sync: {
    guest: 'Хранится только на этом устройстве',
    offline: 'Нет сети. Изменения синхронизируются позже.',
    connecting: 'Подключение…',
    syncing: 'Синхронизация…',
    synced: 'Синхронизировано',
    error: 'Синхронизация приостановлена. Повторяем.',
  },
  syncedAt: (time) => `Синхронизировано в ${time}`,
  favoritesTitle: 'Избранное',
  favoritesEmptyTitle: 'Пока ничего нет',
  favoritesEmptyHint: 'Сохраняйте понравившиеся напитки, и они появятся здесь.',
  findDrink: 'Найти напиток',
  save: 'Сохранить',
  saved: 'Сохранено',
  saveLabel: 'Добавить в избранное',
  unsaveLabel: 'Убрать из избранного',
  madeIt: 'Приготовлено',
  madeItDone: 'Добавлено в историю.',
  swapFind: 'Подобрать замену',
  swapSignInHint: 'Войдите, чтобы получать замены для недостающих ингредиентов.',
  swapPick: 'Какой ингредиент заменить?',
  swapNoIngredients: 'Нет ингредиентов для замены.',
  swapChipLabel: (name: string) => `Подобрать замену: ${name}`,
  swapLoading: 'Подбираем замену',
  swapForTitle: (name: string) => `Замена: ${name}`,
  swapAi: 'Подсказка ИИ',
  swapQuotaReached: 'Дневной лимит ИИ исчерпан. Показываем подборку редакции.',
  swapInBar: 'Есть в баре',
  swapFitClose: 'Близкая замена',
  swapFitWorkable: 'Другой вкус, но подойдёт',
  swapCanSkip: 'Можно и без него.',
  swapEmpty: 'В нашем каталоге нет подходящей замены.',
  swapError: 'Не удалось загрузить замены.',
  swapRetry: 'Повторить',
  swapCount: (n: number) => `Найдено замен: ${n}`,
  todayTab: 'Сегодня',
  searchTab: 'Поиск',
  bartenderTab: 'Бармен',
  bartenderTitle: 'Бармен',
  chatNew: 'Новый чат',
  chatSignedOutTitle: 'Войдите, чтобы спросить бармена',
  chatSignedOutHint:
    'Бармен знает ваш бар и избранное, поэтому ответы подходят к тому, что есть дома.',
  chatSignIn: 'Войти',
  chatSeePick: 'Подборка на сегодня',
  chatEmptyTitle: 'Спросите бармена',
  chatEmptyHint: 'Что приготовить из вашего бара, чем заменить ингредиент, что подойдёт сегодня.',
  chatStarters: [
    'Что я могу приготовить прямо сейчас?',
    'Что-нибудь лёгкое и цитрусовое',
    'Чем заменить вермут в Негрони?',
    'Безалкогольный напиток на вечер',
  ],
  chatAnswering: 'Бармен отвечает\u2026',
  chatPlaceholder: 'Спросите про напитки или замены',
  chatInputLabel: 'Сообщение бармену',
  chatSend: 'Отправить',
  chatYouSaid: 'Вы',
  chatBartenderSaid: 'Бармен',
  chatQuotaLeft: (n: number) =>
    `${pluralCategory('ru', n) === 'one' ? 'Остался' : 'Осталось'} ${n} ${pluralRu(n, 'вопрос', 'вопроса', 'вопросов')} на сегодня \u00b7 Ответы могут быть неточными.`,
  chatQuotaUnknown: 'Ответы могут быть неточными.',
  chatLimitTitle: 'На сегодня все 15 вопросов заданы',
  chatLimitHint:
    'Новые вопросы откроются в полночь. Рецепты, ваш бар и замены из каталога работают как обычно.',
  chatFailTitle: 'Сейчас не удалось ответить',
  chatFailHint: 'Попробуйте через минуту.',
  chatBusyTitle: 'Ещё отвечаем на прошлый вопрос',
  chatRetry: 'Повторить',
  chatTools: {
    get_my_bar: 'Посмотрели ваш бар',
    what_can_i_make: 'Проверили, что можно приготовить',
    search_recipes: 'Поискали рецепты',
    get_recipe: 'Открыли рецепт',
    find_substitutes: 'Подобрали замены',
    recommend_now: 'Подобрали на сейчас',
  },
  kinds: {
    spirit: 'Крепкие',
    liqueur: 'Ликёры',
    wine: 'Вино',
    beer: 'Пиво',
    bitters: 'Биттеры',
    syrup: 'Сиропы',
    juice: 'Соки',
    mixer: 'Миксеры',
    fresh: 'Свежее',
    dairy: 'Молочное',
    pantry: 'Кладовая',
    staple: 'Базовое',
  },
};

export const strings: Record<Locale, Strings> = { en, ru };
