import type { IngredientKind } from '@sipclock/domain';
import { type Locale, pluralCategory } from '@sipclock/i18n';

const pluralRu = (n: number, one: string, few: string, many: string) => {
  const form = pluralCategory('ru', n);
  return form === 'one' ? one : form === 'few' ? few : many;
};

const en = {
  now: 'Now',
  noAlcohol: 'No alcohol',
  makeIt: 'Make it',
  anotherIdea: 'Another idea',
  alsoGoodNow: 'Also good now',
  emptyTitle: 'Nothing fits right now',
  emptyHint: 'Try another occasion or add more to your bar.',
  alcAbbr: 'Alc.',
  freeAbbr: 'Free',
  abvLabel: (percent: number) => `${percent} percent alcohol`,
  alcoholFreeLabel: 'Alcohol free',
  timeLabel: (time: string) => `Current time ${time}`,
  availReady: 'All in your bar',
  availSwap: (n: number) => `Ready · ${n} ${n === 1 ? 'swap' : 'swaps'}`,
  availMissing: (names: string) => `Missing: ${names}`,
  back: 'Back',
  notFoundTitle: 'Drink not found',
  notFoundHint: 'This recipe is not in the catalog.',
  servings: 'Servings',
  decreaseServings: 'Fewer servings',
  increaseServings: 'More servings',
  units: { ml: 'ml', oz: 'oz', parts: 'Parts' } as Record<'ml' | 'oz' | 'parts', string>,
  ingredients: 'Ingredients',
  steps: 'Steps',
  optional: 'optional',
  garnish: 'garnish',
  have: 'In your bar',
  swapWith: (name: string) => `Swap: ${name}`,
  missing: 'Missing',
  barTitle: 'My bar',
  canMakeNow: (n: number) => `${n} ${n === 1 ? 'cocktail' : 'cocktails'} you can make now`,
  searchIngredients: 'Search ingredients',
  starterBar: 'Starter bar',
  clearBar: 'Clear bar',
  clearConfirm: 'Remove everything from your bar?',
  clearYes: 'Clear',
  cancel: 'Cancel',
  noResults: 'No ingredients found.',
  inBarCount: (n: number) => `${n} in your bar`,
  kinds: {
    spirit: 'Spirits',
    liqueur: 'Liqueurs',
    wine: 'Wine',
    beer: 'Beer',
    bitters: 'Bitters',
    syrup: 'Syrups',
    juice: 'Juices',
    mixer: 'Mixers',
    fresh: 'Fresh',
    dairy: 'Dairy',
    pantry: 'Pantry',
    staple: 'Staples',
  } satisfies Record<IngredientKind, string>,
};

export type Strings = typeof en;

const ru: Strings = {
  now: 'Сейчас',
  noAlcohol: 'Без алкоголя',
  makeIt: 'Приготовить',
  anotherIdea: 'Другая идея',
  alsoGoodNow: 'Ещё подойдёт',
  emptyTitle: 'Сейчас ничего не подходит',
  emptyHint: 'Выберите другой повод или пополните бар.',
  alcAbbr: 'Алк.',
  freeAbbr: 'Без алк.',
  abvLabel: (percent) => `${percent} процентов алкоголя`,
  alcoholFreeLabel: 'Без алкоголя',
  timeLabel: (time) => `Сейчас ${time}`,
  availReady: 'Всё есть в баре',
  availSwap: (n) => `Готово · ${n} ${pluralRu(n, 'замена', 'замены', 'замен')}`,
  availMissing: (names) => `Не хватает: ${names}`,
  back: 'Назад',
  notFoundTitle: 'Напиток не найден',
  notFoundHint: 'Этого рецепта нет в каталоге.',
  servings: 'Порции',
  decreaseServings: 'Меньше порций',
  increaseServings: 'Больше порций',
  units: { ml: 'мл', oz: 'oz', parts: 'Части' },
  ingredients: 'Ингредиенты',
  steps: 'Шаги',
  optional: 'по желанию',
  garnish: 'украшение',
  have: 'Есть в баре',
  swapWith: (name) => `Замена: ${name}`,
  missing: 'Нет',
  barTitle: 'Мой бар',
  canMakeNow: (n) =>
    `${n} ${pluralRu(n, 'коктейль', 'коктейля', 'коктейлей')} можно приготовить сейчас`,
  searchIngredients: 'Поиск ингредиентов',
  starterBar: 'Базовый бар',
  clearBar: 'Очистить бар',
  clearConfirm: 'Убрать всё из бара?',
  clearYes: 'Очистить',
  cancel: 'Отмена',
  noResults: 'Ингредиенты не найдены.',
  inBarCount: (n) => `В баре: ${n}`,
  kinds: {
    spirit: 'Крепкие',
    liqueur: 'Ликёры',
    wine: 'Вино',
    beer: 'Пиво',
    bitters: 'Биттеры',
    syrup: 'Сиропы',
    juice: 'Соки',
    mixer: 'Миксеры',
    fresh: 'Свежее',
    dairy: 'Молочное',
    pantry: 'Кладовая',
    staple: 'Базовое',
  },
};

export const strings: Record<Locale, Strings> = { en, ru };
